-- CreateTable
CREATE TABLE "USERS_TABLE" (
    "User_ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "User_Name" TEXT NOT NULL,
    "User_Password" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "BOOK_READING_RECORDS_TABLE" (
    "Record_ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "Record_User_ID" INTEGER NOT NULL,
    "Record_Title" TEXT NOT NULL,
    "Record_Book_Image_Url" TEXT NOT NULL,
    "Record_Content" TEXT,
    "Record_CreateDate" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "Record_UpdateDate" DATETIME NOT NULL,
    CONSTRAINT "BOOK_READING_RECORDS_TABLE_Record_User_ID_fkey" FOREIGN KEY ("Record_User_ID") REFERENCES "USERS_TABLE" ("User_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "USERS_TABLE_User_Name_key" ON "USERS_TABLE"("User_Name");
